# Generated by Django 6.0.2 on 2026-02-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_privacysettings_friends_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountSettings',
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
        migrations.DeleteModel(
            name='PrivacySettings',
        ),
    ]
