# Generated by Django 6.0.2 on 2026-02-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notificationsettings_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='block',
            name='users_block_blocker_0d8572_idx',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='friend',
            name='users_frien_request_7d6457_idx',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='requester',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
