# Generated by Django 6.0.2 on 2026-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_block_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('dnd', 'Do Not Disturb'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
