# Generated by Django 6.0.2 on 2026-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_status',
            field=models.CharField(choices=[('online', 'Online'), ('dnd', 'Do Not Disturb'), ('inactive', 'Inactive'), ('offline', 'Offline')], default='online', help_text='Status before logout', max_length=20),
        ),
    ]
