# Generated by Django 6.0 on 2025-12-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_like_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user', 'comment')},
        ),
    ]
