# Generated by Django 6.0.2 on 2026-02-27 18:28

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.get_message_upload_path),
        ),
    ]
