# Generated by Django 6.0.2 on 2026-02-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_options_alter_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
    ]
