# Generated by Django 6.0.2 on 2026-02-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messageattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='messaging_m_message_276073_idx',
            old_name='messaging_m_message_idx',
        ),
        migrations.RenameIndex(
            model_name='messageattachment',
            new_name='messaging_m_attachm_9ae803_idx',
            old_name='messaging_m_attach_idx',
        ),
    ]
