# Generated by Django 6.0.2 on 2026-02-27 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_block_friend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('color_theme', models.CharField(choices=[('blue', 'Facebook Blue'), ('red', 'Red'), ('green', 'Green'), ('darkblue', 'Dark Blue'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20)),
                ('show_bio', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('show_birth_date', models.BooleanField(default=True)),
                ('show_member_since', models.BooleanField(default=True)),
                ('wall_style', models.CharField(choices=[('classic', 'Classic Wall'), ('compact', 'Compact View'), ('detailed', 'Detailed View')], default='classic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_customization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
