# Generated by Django 6.0.2 on 2026-02-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_profilecustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecustomization',
            name='color_theme',
        ),
    ]
