# Generated by Django 6.0.2 on 2026-02-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0004_remove_profilecustomization_color_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
