# Generated by Django 6.0.2 on 2026-02-28 09:10

import attachments.storage_paths
import attachments.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Maximum file size depends on file type', upload_to=attachments.storage_paths.user_directory_path, validators=[attachments.validators.validate_upload_file]),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['user', '-uploaded_at'], name='attachments_user_id_4476c1_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_type', '-uploaded_at'], name='attachments_file_ty_7bd8ca_idx'),
        ),
    ]
