# Generated by Django 6.0.2 on 2026-02-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notifications_notifi_user_id_db_index',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notifications_notifi_user_id_7f8a9b_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='notifications_notifi_user_id_is_read_8c9d2e_idx',
        ),
    ]
